###############################################################
# Copyright (c) 2021, 2023 Robert Bosch Manufacturing Solutions GmbH
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

{{- $deployment_name := printf "cx-%s-registry" .Release.Name }}
{{- $sec_name := printf "%s-sec" $deployment_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sec_name }}
type: Opaque
data:
  {{- if .Values.enablePostgres }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s-postgresql:%v/%s" .Release.Name .Values.postgresql.service.ports.postgresql .Values.postgresql.auth.database | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.auth.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  {{- else }}
  SPRING_DATASOURCE_URL: {{ .Values.registry.dataSource.url | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.registry.dataSource.user | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.registry.dataSource.password | b64enc }}
  {{- end }}
  {{- if .Values.registry.idpIssuerUri }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.registry.idpIssuerUri | b64enc }}
  {{- else  }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ "http://registry-keycloak/realms/default-realm" | b64enc }}
  {{- end }}
  REGISTRY_IDM_PUBLIC_CLIENT_ID: {{ .Values.registry.idpClientId | b64enc }}
  REGISTRY_IDM_OWNING_TENANT_ID: {{ .Values.registry.tenantId | b64enc }}
